import Head from "next/head";
import About from "../components/About";
import Main from "../components/Main"
import Navbar from "../components/Navbar";
import Skills from "../components/Skills";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Neil Oribello - Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon"/>
      </Head>
      <Navbar/>
      <Main />
      <About />
      <Skills />
      <Projects />
    </div>
  );
}